### PR TITLE
Add local cache

### PR DESCRIPTION
**Pull request by kbudde**
Added a filesystem cache for kubeconfig files.
This cache stores each downloaded file into a local folder to prevent calling the remote too often.
It's needed for #22 / #47 

A memoryCache was also added to prevent duplicate calls to remotes during context selection (preview + download after selection).

### CODE REVIEW

**Comment by danielfoehrKn** [comment]
Thank you! I'll have a look today & sorry for the late response

**Review by danielfoehrKn — APPROVED** [review]
Very nice!

**Comment by danielfoehrKn** [comment]
I think there are missing license headers in two files according to CI

```

Check for license headers
pkg/cache/file/fileCache.go
pkg/cache/memory/memoryCache.go
make: *** [Makefile:26: check] Error 1
```

**Comment by danielfoehrKn** [comment]
Still some unformatted files :) 
```
Executing go vet
Executing gofmt/goimports
Unformatted files detected:
pkg/cache/file/fileCache.go
pkg/cache/memory/memoryCache.go
```

**Comment by kbudde** [comment]
Hey @danielfoehrKn can you run the CI again?
I was running make check locally. It was just showing another missing license header.
I've fixed it. Now it works on my machine.

**Comment by kbudde** [comment]
@danielfoehrKn  and again please :)

I've found the issue. The ci pipeline is using go 1.19. go 1.19 was formatting the license header if there is no empty line before the package. Now it works 👍🏽 (verified on github)

**Comment by danielfoehrKn** [comment]
Great, thanks!

**Pull request merged**
