### PR TITLE
Add Windows version

### PR DESCRIPTION
**Pull request by GuillaumeBernardFGTech**
Hello, thank you for this awesome tool!

As I'm stuck on windows at work, and not allowed to install WSL, I created the necessary powershell script and compiled the tool for windows. 

It really helps me and my colleagues in our day to day work, so we decided to clean it up and submit this PR to help others. 
I use it since 2 month on windows 10 and 11, using windows terminal with powershell 7, it works great. It's even better with Ho My Posh and the kubectl segment to display the current context in the prompt

## What I changed
* Makefile: add Windows AMD64 build
* Github CI: add Windows binary to the release
* Completion.go: Add cobra autocompletion for powershell
* Init.go: add powershell script
* Documentation: add install instructions for windows

## Related issues
* Fixes https://github.com/danielfoehrKn/kubeswitch/issues/64

### CODE REVIEW

**Comment by GuillaumeBernardFGTech** [comment]
For your information, windows defender on my work computer blocks the version 8.0.1 with a low severity. I don't know why. The 8.0 works.

**Comment by zerr0s** [comment]
it would be nice to get a release for all windows users !!

**Comment by ilyesfhi** [comment]
Great job 🔥 ! I hope it will be released soon.

**Comment by GuillaumeBernardFGTech** [comment]
Is the maintainer of the project still here?

**Comment by guillaumebernard84** [comment]
Commenting with my personnal account to get notifications on this pull request

**Comment by danielfoehrKn** [comment]
Thank you for the awesome commit, highly appreciated. Apologize for the long wait. Due to my inactivity, some changes piled up including Linux ARM support which caused merged conflicts when I worked on them in-order. Knowing that it has been a while that you have authored that commit I did not want to bother you with resolving these merge conflicts. I squashed all of your commits into one, resolved the conflicts, added you as commiter and author and pushed the changes to  master [here](https://github.com/danielfoehrKn/kubeswitch/commit/db667a8222045f73074c8ca1193729152f664efb). I hope that is ok with you (you still show up as the author of the commit in Github).

I will also do the necessary changes on the Homebrew side of things and link them here. As your changes are now on master, I'll close this PR and thank you for your patience.

**Pull request closed without merging**
