### PR TITLE
Adds shell completion for bash, zsh & fish

### PR DESCRIPTION
**Pull request by tommy-heyde-olsen**
This PR concludes #52 as well as adding some new features:
- Full tab completion support for bash, zsh & fish
- Refactored all subcommands into own files
- Upgraded to newer version of cobra.
- Bootstraps wrapper script with `switcher init <shell>`
- Updated documentation

### CODE REVIEW

**Comment by tommy-heyde-olsen** [comment]
@danielfoehrKn: This PR is ready now 🚀

**Review by danielfoehrKn — APPROVED** [review]

**Comment by stefanandres** [comment]
Awesome, I cannot wait for a new release to use this :)

**Comment by tommy-heyde-olsen** [comment]
Awesome @danielfoehrKn! 🚀

**Comment by tommy-heyde-olsen** [comment]
@danielfoehrKn: Do I need to do anything to have v0.8.0 released?

**Pull request merged**
